### ISSUE TITLE
Untrusted SSL certificate

### ISSUE THREAD

**Issue by IzK666** [intirix/cloudpasswordmanager#1]
Trying to connect to my own server I get a javax.net.ssl.SSLHandshakeException error.
It's a self-signed server certificate.

**Comment by intirix** [comment]
There are generally two ways to get passed this.  The first is to disable SSL validation.  The second is to do certificate pinning.  Disabling SSL validation for a password manager is not ideal.  I can look into certificate pinning, though.  Basically, there would be a "Pin Certificate" button on the login page.  If you click it, it will download the self-signed certificate and store it locally and use it to validate SSL.  I don't know if that is possible, but I will try to make it happen.

**Comment by intirix** [comment]
@IzK666 

I have published the source code changes to master.  They are waiting approval from Google in the Alpha channel.  I don't have a server with a self-signed cert but I did test it against a valid CA-signed cert on the wrong hostname.  Let me know if this build works.  If it doesn't, I will go back to the drawing board.

https://play.google.com/apps/testing/com.intirix.cloudpasswordmanager

**Comment by IzK666** [comment]
It works fine!!! :smile: 

Thanks!

**Comment by intirix** [comment]
Uploaded 1.1.2 to Play Store
