### ISSUE TITLE
Add Remember Password - When phone has pin set

### ISSUE THREAD

**Issue by AndrewJLowery2** [intirix/cloudpasswordmanager#10]
To enable users to continue using apps like TOTP Second-factor Auth on their owncloud account, it would be useful if the app could remember the password, but only if the phone has a pin/password set.

OwnCloud;s 'App passwords' are long and not configurable for example XRNRR-AXHKL-OTTAB-BBMJR.

**Comment by intirix** [comment]
What Android version (API version) do you use?  I am just trying to figure out what technology is available to me to securely store the password.

**Comment by AndrewJLowery2** [comment]
KitKat  4.4 - 4.4.4 API level 19

**Comment by intirix** [comment]
I have added a new Settings page.  Once you log into the app, open the left hand menu.  In the settings page, you can change the "Password Policy".  

I have submitted v1.3.0 to the Play Store in the Alpha channel.  Source code is posted in the release_v1_3_x branch.

**Comment by intirix** [comment]
This is live in the app store.
