### ISSUE TITLE
can not login illegal state

### ISSUE THREAD

**Issue by pafcioooo** [intirix/cloudpasswordmanager#13]
While trying to login it seems that credentails are working but after a whwhile it show login screen again with en error:
" Failed: java.lang.illegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $

App version 1.3.1 built 2016/11/26 16:24:35 CET

**Comment by pafcioooo** [comment]
This is duplicate of #11 .

**Comment by intirix** [comment]
I never got a response from the passwords developer, so I'm going to just assume it is an API change.  I can only version check it, which means I might break earlier v20 betas

**Comment by e-alfred** [comment]
Well, he wasn't very cooperative anyway, here is the new place for the app: 
https://github.com/marius-wieschollek/passwords

Maybe you can ask the new maintainer to help make it compatible again?

**Comment by intirix** [comment]
I pushed a new version to the Play Store that should resolve this issue
