### ISSUE TITLE
Passwords API version 21 

### ISSUE THREAD

**Issue by marius-wieschollek** [intirix/cloudpasswordmanager#14]
I maintain the Nextcloud compatible fork of Fallon Turners Passwords app for OwnCloud. As you might know, the original app is no longer maintained. Because of that i am asking you as one of the projects that use the api about a breaking change i would like to make.

The original api 20-beta8 provides a "properties" attribute for each password. This attribute should be a JSON encoded object, but contains invalid JSON instead that often needs to be fixed before it can be decoded.

The change i would like to make is to provide a valid JSON encoded object in the properties string by default. This makes it easier to use the API and it also would make it easier to maintain the implementation in the rewritten backend. I would also set the version to 21 to make this change clear. 

These changes can already be found in the [new app](https://github.com/marius-wieschollek/passwords) and will be implemented to the [old app](https://github.com/marius-wieschollek/passwords-legacy).
Would you be willing to implement this change in your App?

**Comment by intirix** [comment]
That shouldn't be too hard to do.  I can make the change.

**Comment by marius-wieschollek** [comment]
That sounds great. Then i will try to port the changes to the old app and provide an updated documentation.

**Comment by intirix** [comment]
1.4.3 has been released to the store.  It should support both API formats.  It tries to detect the format rather than using a version check
