### ISSUE TITLE
Number and symbol detection

### ISSUE THREAD

**Issue by IzK666** [intirix/cloudpasswordmanager#2]
This issue is related to the type of characters used in the pass (lower, upper, numbers and symbols). The passwords are displayed fine.

When the password contains numbers and no symbols, the booleans for numbers and symbols are disabled!
When the password contains symbols and no numbers, the booleans for symbols and numbers are enabled.

**Comment by intirix** [comment]
I am passing the values straight through from the Passwords REST API.  I just took a look and I can see the bug in the Passwords app.  I will pass it along to upstream.

**Comment by ghost** [comment]
I fixed this. Thanks for catching that!
