### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by roru69** [intirix/cloudpasswordmanager#6]
Hi there,

I know the app isn't feature complete, but i would like to have a search option. Very handy when you have a lot of passwords to scroll though.

Kind Regards RR69

**Comment by intirix** [comment]
This was surprisingly easy.  I knocked it out in three hours.  Commit cf250b206470282a85c648b756c919d82e9dd50d is being published to the Alpha channel

**Comment by intirix** [comment]
Fixed bug where clicking on filtered search items takes you to the wrong item
fd09cc0b23361f8abe0dfcf6ea76372197c87739
