### ISSUE TITLE
owncloud passwords app fails to load content

### ISSUE THREAD

**Issue by AndrewJLowery2** [intirix/cloudpasswordmanager#9]
I have installed the owncloud passwords app and installed the cloudpasswordmanager.

When I try to connect from my android, it fails and stays loading before returning to the login screen?

**Comment by intirix** [comment]
I have a few questions:

Did you get any errors?  Errors usually show up under the login form.
What version of Owncloud are you using?
What version of Passwords are you using?
I'm assuming you are using the 1.2.1 version of the app.  The About screen in the left hand nav will tell you.
Are you using SSL?
If so, is it a valid or self-signed cert?
Are you using the Cert pinning feature?
Can you validate that your URL is correct?  If you install owncloud in /owncloud, then that should be the url to use.  For example: https://www.example.com/owncloud

**Comment by AndrewJLowery2** [comment]
No error it moves on to the next Activity and then the loading icon appears for about 1 minute and then returns to the login page.
ownCloud 9.1.1 (stable)
Passwords v19
app 1.2.1
yes
Trusted Cert
Are you using the Cert pinning feature - Not sure what this is?
the url is correct and I see the same error on https://www.example.com/owncloud https://www.example.com/

**Comment by intirix** [comment]
Without an error message, there isn't much I can do.  The error message should appear in grey under the password field, but above the "PIN SSL" button.  When I go to https://www.example.com/owncloud, I get an error of "404: Not Found".

I have not tried against ownCloud 9.1.1 yet.  My personal install is still on 9.0.2.  I have a DEV environment that I can upgrade to try it out there.  It will be some time before I can get into that environment and upgrade it, though.

**Comment by AndrewJLowery2** [comment]
After a little more testing I have found that the issue is due to the notes field on the entries, and can be recreated if you add this to string to any note 

:^$.| ? \* + () [ {

seems to be a bug.

**Comment by AndrewJLowery2** [comment]
in fact just add a backslash into the notes field

\

**Comment by intirix** [comment]
Thanks for the research.  I tested it in my dev owncloud server and reproduced the issue.  I think there are actually two issues here.  One is in the passwords app in how it generates json (json within json).  The second is with my app.  The REST API returns json that contains json inside of it.  It looks like I'm not reporting errors when parsing the inside json.

Here is an example
Notes is "test \ test"

Here is what I get.  The value of "properties" is {"notes" : "test \ test"} which is not valid json
{
 "properties": "{\"notes\" : \"test \ test\"}"
}

Here is what it should be.  The value of "properties" is {"notes" : "test \ test"}
{
 "properties": "{\"notes\" : \"test \\ test\"}"
}

I will fix the error messaging and report an issue to fcturner

**Comment by AndrewJLowery2** [comment]
Great, Thank you
